1. db.restaurants.find({})
2. db.restaurants.find({},{restaurant_id:1, name:1, borough:1, cuisine:1})
3. db.restaurants.find({},{restaurant_id:1, name:1, borough:1, cuisine:1, _id:0})
4. db.restaurants.find({},{restaurant_id:1, name:1, borough:1, address:{zipcode:1}, _id:0})
5. db.restaurants.find({borough:"Bronx"})
6. db.restaurants.find({borough:"Bronx"}).limit(5)
7. db.restaurants.find({borough:"Bronx"}).skip(5).limit(5)
13. db.restaurants.find({$and:[{cuisine:{$ne:"American "}},{borough:{$ne:"Brooklyn"}}]}).sort({cuisine:-1})
14. db.restaurants.find({name: {'$regex':'^Wil'}},{restaurant_id:1, name:1, borough:1, cuisine:1, _id:0})
15. db.restaurants.find({name: {'$regex':'ces$'}},{restaurant_id:1, name:1, borough:1, cuisine:1, _id:0})
16. db.restaurants.find({name: /Reg/},{restaurant_id:1, name:1, borough:1, cuisine:1, _id:0})
17. db.restaurants.find({$and:[{  $or:[ {cuisine:"American "},{cuisine:"Chinese"}]},{borough:"Bronx"}]})
18. db.restaurants.find({$or:[{borough:"Brooklyn"},{borough:"Bronx"}, {borough:"Staten Island"}, {borough:"Queens"}]},{restaurant_id:1, name:1, borough:1, cuisine:1, _id:0})
19. db.restaurants.find({borough:{ $nin : ["Staten Island","Queens", "Bronx","Brooklyn"]}},{restaurant_id:1, name:1, borough:1, cuisine:1, _id:0})
25. db.restaurants.find({}).sort({name:1})
26. db.restaurants.find({}).sort({name:-1})
27. db.restaurants.find({}).sort({cuisine:1}).sort({borough:-1})


